-define(KRL_SECTION_CERTIFICATES, 1).
-define(KRL_SECTION_EXPLICIT_KEY, 2).
-define(KRL_SECTION_FINGERPRINT_SHA1, 3).
%% not implemented -define(KRL_SECTION_SIGNATURE, 4).
-define(KRL_SECTION_FINGERPRINT_SHA256, 5).
-define(KRL_SECTION_EXTENSION, 255).

-define(KRL_SECTION_CERT_SERIAL_LIST, 16#20).
-define(KRL_SECTION_CERT_SERIAL_RANGE, 16#21).
-define(KRL_SECTION_CERT_SERIAL_BITMAP, 16#22).
-define(KRL_SECTION_CERT_KEY_ID, 16#23).
-define(KRL_SECTION_CERT_EXTENSION, 16#39).
